[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# Configuration des formulaires
[forms]
  # Configuration par défaut pour tous les formulaires
  [forms.settings]
    # Email de notification par défaut
    notification_email = "duvalgirardjules@gmail.com"
    # Activation des notifications
    enabled = true
    # Sujet personnalisé pour les notifications
    subject_prefix = "[MCBoutin Contact]"
